version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URI=mysql+pymysql://your_user:your_password@db/your_database
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
